site_name: 'Raspberry PI k3s stories'
dev_addr: '127.0.0.1:8100'
docs_dir: docs/
site_dir: site/
repo_name: 'gdha/pi-stories'
repo_url: 'https://github.com/gdha/pi-stories'
copyright: 'Copyright 2023 - CC0 1.0 Universal'

theme:
  name: 'readthedocs'
markdown_extensions:
  - toc:
      permalink: True
      separator: "_"
nav:
  - WELCOME: 'index.md'
  - PI4 STORIES:
    - 'Raspberry Pi 4 Basic OS Configuration': 'pi-stories1.md'
    - 'Raspberry Pi 4 Prepare for kubernetes': 'pi-stories2.md'
    - 'Raspberry Pi 4 Installing k3s software': 'pi-stories3.md'
    - 'Raspberry Pi 4 Install awesome kubectl aliases': 'pi-stories4.md'
    - 'Raspberry Pi 4 Installing cert-manager on our cluster': 'pi-stories5.md'
    - 'Raspberry Pi 4 Upgrading k3s software on your cluster': 'pi-stories6.md'
    - 'Raspberry Pi 4 YAML everywhere -what about correctness?': 'pi-stories7.md'
    - 'Raspberry Pi 4 Keep your Operating System updated': 'pi-stories8.md'
    - 'Raspberry Pi 4 Installation of Longhorn': 'pi-stories9.md'
    - 'Raspberry Pi 4 Issues after upgrading k3s': 'pi-stories10.md'
    - 'Raspberry Pi 4 Replacing internal traefik with Metallb': 'pi-stories11.md'
    - 'Raspberry Pi 4 Spin up graphite and temperature2celsius pods': 'pi-stories12.md'
    - 'Raspberry Pi 4 Setup monitoring': 'pi-stories13.md'
    - 'Raspberry Pi 4 Setup logging with Loki': 'pi-stories14.md'
    - 'Raspberry Pi 4 Troubleshooting': 'pi-stories15.md'
    - 'Raspberry Pi 4 Deploying uptime kuma with helm': 'pi-stories16.md'


